export const tagOptions = [
  { value: "Indie", label: "Indie" },
  { value: "Action", label: "Action" },
  { value: "Adventure", label: "Adventure" },
  { value: "Casual", label: "Casual" },
  { value: "Singleplayer", label: "Singleplayer" },
  { value: "Strategy", label: "Strategy" },
  { value: "Simulation", label: "Simulation" },
  { value: "RPG", label: "RPG" },
  { value: "Multiplayer", label: "Multiplayer" },
  { value: "Great Soundtrack", label: "Great Soundtrack" },
  { value: "Atmospheric", label: "Atmospheric" },
  { value: "2D", label: "2D" },
  { value: "Puzzle", label: "Puzzle" },
  { value: "Early Access", label: "Early Access" },
  { value: "Open World", label: "Open World" },
  { value: "Story Rich", label: "Story Rich" },
  { value: "Co-op", label: "Co-op" },
  { value: "Difficult", label: "Difficult" },
  { value: "Shooter", label: "Shooter" },
  { value: "Sci-fi", label: "Sci-fi" },
  { value: "First-Person", label: "First-Person" },
  { value: "Horror", label: "Horror" },
  { value: "Anime", label: "Anime" },
  { value: "Pixel Graphics", label: "Pixel Graphics" },
  { value: "VR", label: "VR" },
  { value: "Funny", label: "Funny" },
  { value: "Platfromer", label: "Platfromer" },
  { value: "Fantasy", label: "Fantasy" },
  { value: "Free to Play", label: "Free to Play" },
  { value: "Female Protagonist", label: "Female Protagonist" },
  { value: "FPS", label: "FPS" },
  { value: "Gore", label: "Gore" },
  { value: "Survival", label: "Survival" },
  { value: "Violent", label: "Violent" },
  { value: "Sandbox", label: "Sandbox" },
  { value: "Retro", label: "Retro" },
  { value: "Arcade", label: "Arcade" },
  { value: "Comedy", label: "Comedy" },
  { value: "Classic", label: "Classic" },
  { value: "Nudity", label: "Nudity" },
  { value: "Third Person", label: "Third Person" },
  { value: "Massively Multiplayer", label: "Massively Multiplayer" },
  { value: "Exploration", label: "Exploration" },
  { value: "Point & Click", label: "Point & Click" },
  { value: "Visual Novel", label: "Visual Novel" },
  { value: "Turn-Based", label: "Turn-Based" },
  { value: "Space", label: "Space" },
  { value: "Sports", label: "Sports" },
  { value: "Rogue-like", label: "Rogue-like" },
  { value: "Racing", label: "Racing" }
];
